
/**************************************************************
 *	
 *	Ah, 8 bit, 11025Hz,
 *	1 channel, 423057 bytes/channel
 *	Total Size: 1 * 423057 + 4 (header) = 423101 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jodiannebartolo/Desktop/Fall2019/CS2261/LactoseGame/Ah.wav
 *	Time-stamp: Tue Nov 19 10:38:49 2019
 *	
 **************************************************************/

#ifndef __AHH__
#define __AHH__

#define AHFREQ 11025
#define AHLEN 423057

extern const unsigned char Ah[423057];

#endif /* __AHH__ */
