
/**************************************************************
 *	
 *	catchmusic2, 8 bit, 11025Hz,
 *	1 channel, 103765 bytes/channel
 *	Total Size: 1 * 103765 + 4 (header) = 103809 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jodiannebartolo/Desktop/Fall2019/CS2261/LactoseGame/catchmusic2.wav
 *	Time-stamp: Wed Dec 04 22:48:47 2019
 *	
 **************************************************************/

#ifndef __CATCHMUSIC2H__
#define __CATCHMUSIC2H__

#define CATCHMUSIC2FREQ 11025
#define CATCHMUSIC2LEN 103765

extern const unsigned char catchmusic2[103765];

#endif /* __CATCHMUSIC2H__ */
