
/**************************************************************
 *	
 *	catchmusic, 8 bit, 11025Hz,
 *	1 channel, 311294 bytes/channel
 *	Total Size: 1 * 311294 + 4 (header) = 311338 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jodiannebartolo/Desktop/Fall2019/CS2261/LactoseGame/catchmusic.wav
 *	Time-stamp: Tue Dec 03 15:46:19 2019
 *	
 **************************************************************/

#ifndef __CATCHMUSICH__
#define __CATCHMUSICH__

#define CATCHMUSICFREQ 11025
#define CATCHMUSICLEN 311294

extern const unsigned char catchmusic[311294];

#endif /* __CATCHMUSICH__ */
