
/**************************************************************
 *	
 *	drivemusic, 8 bit, 11025Hz,
 *	1 channel, 415059 bytes/channel
 *	Total Size: 1 * 415059 + 4 (header) = 415103 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jodiannebartolo/Desktop/Fall2019/CS2261/LactoseGame/drivemusic.wav
 *	Time-stamp: Wed Dec 04 21:07:15 2019
 *	
 **************************************************************/

#ifndef __DRIVEMUSICH__
#define __DRIVEMUSICH__

#define DRIVEMUSICFREQ 11025
#define DRIVEMUSICLEN 415059

extern const unsigned char drivemusic[415059];

#endif /* __DRIVEMUSICH__ */
