
/**************************************************************
 *	
 *	iceMAnVO, 8 bit, 11025Hz,
 *	1 channel, 75796 bytes/channel
 *	Total Size: 1 * 75796 + 4 (header) = 75840 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jodiannebartolo/Desktop/Fall2019/CS2261/LactoseGame/iceMAnVO.wav
 *	Time-stamp: Tue Nov 26 12:15:24 2019
 *	
 **************************************************************/

#ifndef __ICEMANVOH__
#define __ICEMANVOH__

#define ICEMANVOFREQ 11025
#define ICEMANVOLEN 75796

extern const unsigned char iceMAnVO[75796];

#endif /* __ICEMANVOH__ */
