
/**************************************************************
 *	
 *	yumm, 8 bit, 11025Hz,
 *	1 channel, 6264 bytes/channel
 *	Total Size: 1 * 6264 + 4 (header) = 6308 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/jodiannebartolo/Desktop/Fall2019/CS2261/LactoseGame/yumm.wav
 *	Time-stamp: Thu Dec 05 00:14:31 2019
 *	
 **************************************************************/

#ifndef __YUMMH__
#define __YUMMH__

#define YUMMFREQ 11025
#define YUMMLEN 6264

extern const unsigned char yumm[6264];

#endif /* __YUMMH__ */
